### Performin EDA in best Possible way using Pandas Profiling

In [2]:
import numpy as np
import pandas as pd
from ydata_profiling import ProfileReport

C:\Users\ZBook\AppData\Local\Temp\ipykernel_2332\484894876.py:3: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

In [3]:
pip show ydata-profiling

Name: ydata-profiling
Version: 4.18.4
Summary: Generate profile report for pandas DataFrame
Home-page: https://ydata.ai
Author:
Author-email: YData Labs Inc <opensource@ydata.ai>
License:
Location: D:\Anaconda3\Lib\site-packages
Requires: dacite, filetype, imagehash, jinja2, matplotlib, minify-html, multimethod, numba, numpy, pandas, phik, pydantic, PyYAML, requests, scipy, seaborn, statsmodels, tqdm, typeguard, visions, wordcloud
Required-by:
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~atplotlib (D:\Anaconda3\Lib\site-packages)

In [4]:
from sklearn.datasets import load_diabetes

In [5]:
diab_data=load_diabetes()
df=pd.DataFrame(data=diab_data.data , columns=diab_data.feature_names)

In [6]:
df.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641

In [7]:
df.columns

Index(['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6'], dtype='object')

#### Apply Pandas Profiling to generate report quickly

In [8]:
profile=ProfileReport(df , title='PAndas Profiling Report' ,explorative=True)

In [20]:
# #Show report in Notebook
# profile.to_widgets()

In [10]:
#save report in html file externalyy
profile.to_file("EDA_Report.html")

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

#### Perform Pandas profiling on Titanic dataset

In [14]:
df1=pd.read_csv('train.csv')

In [15]:
df1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [16]:
profile_1=ProfileReport(df1 , title='Pandas Profiling On Titanic' ,explorative=True)

In [19]:
profile_1.to_file('TITANIC.html')

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]